### ISSUE TITLE
Training improvements

### ISSUE THREAD

**Issue by n1t0** [huggingface/tokenizers#528]
This issue is here to keep track of the different subjects around training.

- [x] Ability to train from memory (#198)
- [ ] Ability to re-train a Tokenizer with relevant parameters (#525)
- [x] Extract the word-counts to each Trainer (#524)
- [ ] AddedVocabulary does not play well with the Model (#523)
- [x] Trainer trains the Model in-place (#526)
- [x] Make the `trainer` optional when training (#527)
